### PR TITLE
Deps updates, transpec and ruby 2.0 signature for respond_to?()

### PR DESCRIPTION
**Pull request by atz**
note: respond_to? is expected to take 2 args in ruby 2.0+

### CODE REVIEW

**Comment by atz** [comment]
Build failures are related to **jruby-19mode** and include pending-but-passing tests.  Rspec 3 considers these an error -- i.e., they aren't `pending` anymore.  

For totally unimplemented tests, the newer convention is to mark them `skip`.

Other failures might require attention from someone with jruby-19 experience or interest.

**Comment by atz** [comment]
Last remaining failure is under jruby-19 is:
```
1) Nutrition #add_terminology_method_overrides! should let you override the warning
Failure/Error: expect { document.a.first.add_terminology_method_overrides! }.to_not raise_error
expected no Exception, got #<SystemStackError: stack level too deep> with backtrace:
 # ./spec/lib/terminology_decorator_spec.rb:48:in `(root)'
 # ./spec/lib/terminology_decorator_spec.rb:48:in `(root)'
```
Likely platform specific recursion?  Not sure what the point of "platform compatibility" is if we are outright breaking on that platform (but hiding the problem in rspec with JRUBY_VERSION sniffing).

**Comment by cbeer** [comment]
Looks like 1.8 is also busted. I'm happy  to drop both 1.8 and jruby from CI if you want.

**Comment by atz** [comment]
Will definitely drop 1.8.  Has been end-of-life for over half a year.  Open to modern jruby if anybody has a need for it.

**Comment by cbeer** [comment]
:+1:

**Pull request merged**
